export enum NotificationTypeEnum {
  ORDER_PLACED = 'ORDER_PLACED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  ESCROW_RELEASED = 'ESCROW_RELEASED',
  PAYOUT_PROCESSED = 'PAYOUT_PROCESSED',
}
